name: Export Framaforms data

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

env:
  FORM_USER: ${{ secrets.FORM_USER }}
  FORM_PWD: ${{ secrets.FORM_PWD }}
  FORM_ID: ${{ secrets.FORM_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Prepare node tools
        run: npm i -g yarn && yarn install
      - name: Export & extract framaforms data
        run: yarn pipe-all
      - name: Deploy on ftp
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          protocol: ftp
          port: 21
          local-dir: "./to-export/"
          server-dir: "www/data/"