name: Export Framaforms data

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build app
        run: npm i -g yarn && yarn install && yarn pipe-all
      - name: Deploy on ftp
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          protocol: ftp
          port: 21
          local-dir: "./to-export/"
          server-dir: "www/data/"